// Unit tests for the dashboard's pure rules — dates, the cohort status ladder,
// search, aggregation and per-source column tracking.
//
//   node test_dashboard_logic.js
//
// operations_dashboard.js is a browser IIFE, so this stubs just enough DOM for it to
// load and uses a fixed miniature dataset rather than the generated operations_data.js:
// the tracker is regenerated by a separate process, and a test that moves with
// the data cannot tell a regression from a data change.
// Minimal DOM stub so the dashboard module can be required in Node.
const FIXTURE = {
  referenceDate: '2026-09-11',
  fieldsPresent: {
    tracker: ['first','last','startDate','cohortDate','slack','managerEmailSent','kitOrdered',
              'googleGroup','deviceShipDate','oktaActivated','personalEmail','managerName','location'],
    archive: ['first','last','startDate','cohortDate','slack','managerEmailSent','kitOrdered',
              'googleGroup','deviceShipDate','oktaActivated','personalEmail','managerName','location',
              'welcomeCallSent']
  },
  hires: [{ first:'A', last:'B', name:'A B', startDate:'2026-09-08', cohortDate:'2026-09-08',
            offCycle:false, source:'tracker', fn:'Engineering', region:'United States' }],
  sessions: [], attendance: [], pilot: [], automation:{manual:[],automated:[]}
};

const noop = () => {};
const el = () => ({ style:{}, classList:{add:noop,remove:noop,toggle:()=>false,contains:()=>false},
  appendChild:noop, setAttribute:noop, addEventListener:noop, focus:noop,
  querySelectorAll:()=>[], querySelector:()=>null, getBoundingClientRect:()=>({left:0,top:0,width:0,height:0}),
  firstChild:null, removeChild:noop, textContent:'' });
global.document = { createElement: el, createTextNode: t=>({t}), getElementById: el,
  addEventListener: noop, querySelectorAll: ()=>[] };
global.window = { addEventListener: noop, ONBOARDING_DATA: FIXTURE, innerWidth:1400, innerHeight:900,
  scrollTo: noop };
global.location = { hash: '' };
global.navigator = {};
global.setTimeout = setTimeout;

const M = require('./operations_dashboard.js');

let pass = 0, fail = 0;
function is(actual, expected, label) {
  const ok = JSON.stringify(actual) === JSON.stringify(expected);
  if (ok) { pass++; } else { fail++; console.log('  FAIL', label, '=> got', JSON.stringify(actual), 'want', JSON.stringify(expected)); }
}

// --- date arithmetic across month and year boundaries -----------------------
is(M.addDays('2026-01-31', 1),  '2026-02-01', 'addDays end of Jan');
is(M.addDays('2026-02-28', 1),  '2026-03-01', 'addDays end of Feb (non-leap)');
is(M.addDays('2026-12-31', 1),  '2027-01-01', 'addDays across new year');
is(M.addDays('2026-09-11', -14),'2026-08-28', 'addDays negative across month');
is(M.addDays('2026-03-08', 13), '2026-03-21', 'addDays DST weekend (US spring forward)');
is(M.addDays('2026-11-01', 13), '2026-11-14', 'addDays DST weekend (US fall back)');
is(M.ym('2026-09-14'), '2026-09', 'ym');

// --- the cohort status ladder, reference date 2026-09-11 --------------------
// (TODAY comes from the shim below)
is(M.cohortStatus('2026-09-08', '2026-09-21'), 'active',    'started, inside 14-day window');
// The window is start + 13 days inclusive, i.e. 14 calendar days. With the
// reference date 2026-09-11 the last cohort still inside it started 2026-08-29.
is(M.cohortStatus('2026-08-29', '2026-09-21'), 'active',    'last day of the 14-day window');
is(M.cohortStatus('2026-08-28', '2026-09-21'), 'completed', 'one day past the window');
is(M.cohortStatus('2026-09-11', '2026-09-21'), 'active',    'starts today = active');
is(M.cohortStatus('2026-09-21', '2026-09-21'), 'next',      'first cohort on/after today');
is(M.cohortStatus('2026-10-05', '2026-09-21'), 'upcoming',  'later cohort');

// --- search --------------------------------------------------------------
const hire = { name:"Aisha O'Brien", jobTitle:'Staff Engineer', managerName:'Riley Chen',
  recruiter:'Elena Voss', hrbp:'HRBP B', department:'Engineering', fn:'Engineering',
  location:'Berlin, Germany', workEmail:'a@b.c', personalEmail:'', region:'Other / International',
  pilotTrack:'', source:'tracker' };
is(M.searchMatch(hire, 'riley'),   true,  'search matches manager, case-insensitive');
is(M.searchMatch(hire, "o'brien"), true,  'search handles an apostrophe in a name');
is(M.searchMatch(hire, 'HRBP B'),  true,  'search matches HRBP');
is(M.searchMatch(hire, 'zzz'),     false, 'search rejects a non-match');
is(M.searchMatch(hire, ''),        true,  'empty query matches everything');

// --- aggregation ----------------------------------------------------------
is(M.tally([{a:'x'},{a:'y'},{a:'x'}], r=>r.a), {x:2,y:1}, 'tally counts');
is(M.tally([{r:['p','q']},{r:['p']}], r=>r.r), {p:2,q:1}, 'tally splits array keys (multi-recruiter)');
is(M.byCountDesc({a:1,b:3,c:3}), ['b','c','a'], 'byCountDesc, ties alphabetical');

// --- off-cycle operational date -------------------------------------------
is(M.opDate({offCycle:true,  startDate:'2026-09-24', cohortDate:'2026-09-28'}), '2026-09-24', 'off-cycle anchors to joining date');
is(M.opDate({offCycle:false, startDate:'2026-09-21', cohortDate:'2026-09-21'}), '2026-09-21', 'main anchors to cohort date');

// --- per-source column tracking -------------------------------------------
is(M.trackedFor('welcomeCallSent', 'tracker'), false, 'untracked column is not a missed step');
is(M.trackedFor('welcomeCallSent', 'archive'), true,  'same column IS tracked in the archive');
is(M.trackedFor('slack', 'tracker'),           true,  'tracked column reads normally');
is(M.trackedFor('anything', 'unknown-source'), true,  'unknown provenance assumes tracked');

// --- readiness ------------------------------------------------------------
const full = { source:'tracker', managerEmailSent:true, welcomeCallSent:false, slack:true,
               googleGroupDone:true, kitOrdered:true, deviceShipDate:'2026-09-01' };
const r = M.readiness(full);
is(r.total < M.STEPS.length, true, 'untracked step drops out of the denominator');
is(r.done, r.total, 'all tracked steps complete = 100%');
is(M.groupReadiness([]), 0, 'empty group does not divide by zero');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
